### ISSUE TITLE
Time Extension

### ISSUE THREAD

**Issue by Filienko** [drivendataorg/nasa-pushback-runtime#6]
In the competition guidance page, you seemed to indicate that the 10 hours limit to the execution time was implemented primarily to prevent a script without an appropriate termination condition from taking on the execution resources. If our prescreened script may require more than 10 hours to execute, depending on environment, could we potentially request that additional time being granted?

**Comment by r-b-g-b** [comment]
At this late stage, we have decided to keep the time limit at 10 hours.

We want to keep things fair for participants who may have tailored their approach to work within the time limit and who at this point do not have much time to update their algorithms in response to a change in that constraint. I hope you understand our rationale and are able to find a way to make your submission run in the allotted time!
